/**
 * Exports the full schema as a single SQL file for pasting into a database
 * console (Neon, psql, TablePlus).
 *
 * `npm run db:migrate` remains the better path — it does this and records
 * state correctly on its own. This exists for the case where you only have a
 * SQL console.
 *
 * The bookkeeping section at the end is the part that is easy to get wrong.
 * Drizzle decides what to apply by comparing the journal's `when` timestamp
 * against the newest `created_at` in `drizzle.__drizzle_migrations` — not by
 * hash. Fabricating those timestamps makes the next `db:migrate` re-run every
 * migration and fail on tables that already exist, so they are read from the
 * journal rather than invented.
 *
 * Usage: npm run db:export
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const drizzleDir = join(root, 'drizzle');

const journal = JSON.parse(
  readFileSync(join(drizzleDir, 'meta', '_journal.json'), 'utf8'),
);

const migrations = journal.entries.map((entry) => {
  const file = `${entry.tag}.sql`;
  const raw = readFileSync(join(drizzleDir, file), 'utf8');

  return {
    file,
    when: entry.when,
    // Drizzle hashes the raw file contents.
    hash: createHash('sha256').update(raw).digest('hex'),
    sql: raw.split('--> statement-breakpoint').join('').trim(),
  };
});

const rule = (label) => `-- ${'─'.repeat(74)}\n-- ${label}\n-- ${'─'.repeat(74)}`;

const out = `-- ===========================================================================
-- FamLink — complete schema
--
-- Generated by \`npm run db:export\` from drizzle/*.sql. Do not edit by hand;
-- edit lib/db/schema.ts and regenerate.
--
-- Run against the UNPOOLED connection — the Neon host WITHOUT "-pooler".
-- DDL through PgBouncer in transaction mode is unreliable.
--
-- ${migrations.length} migrations · 23 tables · 10 enums
-- ===========================================================================


${rule('1. DESTRUCTIVE RESET — commented out deliberately')}
--
-- Uncomment ONLY to wipe an existing database. There is no undo: this deletes
-- every location, message and emergency record permanently.
--
-- Skip this entire section on a fresh database.

-- DROP SCHEMA IF EXISTS drizzle CASCADE;
-- DROP SCHEMA public CASCADE;
-- CREATE SCHEMA public;


${rule('2. SCHEMA')}

BEGIN;

${migrations
  .map((m) => `\n-- ─── ${m.file} ───\n\n${m.sql}\n`)
  .join('\n')}

${rule('3. MIGRATION BOOKKEEPING')}
--
-- Records these migrations as applied. Without it, the next
-- \`npm run db:migrate\` re-runs everything above and fails on existing tables.
--
-- The timestamps must match drizzle/meta/_journal.json exactly — Drizzle
-- compares them, not the hashes, when deciding what to apply.

CREATE SCHEMA IF NOT EXISTS drizzle;

CREATE TABLE IF NOT EXISTS drizzle.__drizzle_migrations (
  id SERIAL PRIMARY KEY,
  hash text NOT NULL,
  created_at bigint
);

INSERT INTO drizzle.__drizzle_migrations (hash, created_at) VALUES
${migrations.map((m) => `  ('${m.hash}', ${m.when})`).join(',\n')};

COMMIT;


-- ===========================================================================
-- Verify:
--   SELECT count(*) FROM information_schema.tables WHERE table_schema='public';
--   -- expect 23
-- ===========================================================================
`;

writeFileSync(join(root, 'deploy-schema.sql'), out);

console.log(`Wrote deploy-schema.sql`);
for (const m of migrations) {
  console.log(`  ${m.file.padEnd(38)} ${m.hash.slice(0, 12)}…  ${m.when}`);
}
